homepage: "https://lumio.dev"
language: rust
primary_contact: "gerardo@lumiolabs.com"
main_repo: "https://github.com/lumio-labs/lumio-core"
auto_ccs:
  - "oss-fuzz-notifications@lumiolabs.com"
  - "security@lumiolabs.com"
  - "andrea.cappa@lumiolabs.com"
  - "marco.ilardi@lumiolabs.com"
sanitizers:
  - none
fuzzing_engines:
  - libfuzzer
coverage_extra_args: -ignore-filename-regex=.*/rustc/.*
