{
 "title": "fullnodes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "State Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State Sync Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lumio_state_sync_version{type=\"synced\", kubernetes_pod_name=~\"$kubernetes_pod_name\", kubernetes_pod_name=~\".*fullnode.*\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Fullnodes lagging behind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(lumio_data_client_highest_advertised_data{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",  role=\"validator_fullnode\", data_type=\"transactions\"}  - on(kubernetes_pod_name,role,run_uuid) lumio_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"telemetry-service\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=\"validator_fullnode\", type=\"synced\"} > 50000)  OR on() vector(0)",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "State Sync Rate",
   "type": "graph",
   "description": "Rate at which the synced version is increasing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"synced\", kubernetes_pod_name=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(lumio_state_sync_version{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", type=\"synced\", job=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{job}}"
    }
   ]
  },
  {
   "title": "Fullnode Upstream Peers",
   "type": "graph",
   "description": "Number of upstream peers that can provide up to date information about the ledger.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, network_id)(lumio_connections{kubernetes_pod_name=~\"$kubernetes_pod_name\", kubernetes_pod_name=~\".*fullnode.*\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Mempool Pending transactions",
   "type": "graph",
   "description": "Number of uncommitted but still valid (not expired nor discarded) transactions in the nodes Mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lumio_core_mempool_index_size{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", index=\"system_ttl\", kubernetes_pod_name=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "lumio_core_mempool_index_size{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", index=\"system_ttl\", job=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{job}}"
    }
   ]
  },
  {
   "title": "Mempool Txn Commit Latency",
   "type": "graph",
   "description": "The time between Mempool receiving the transaction and time to be committed. Note: due to reliability mechanisms, this value can be lower than it really is.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "lumio_core_mempool_txn_commit_latency_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} / lumio_core_mempool_txn_commit_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "lumio_core_mempool_txn_commit_latency_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", job=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} / lumio_core_mempool_txn_commit_latency_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", job=~\".*fullnode.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{job}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network Connections (Incoming)",
   "type": "graph",
   "description": "Number of Inbound Connections as measured by LumioNet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,kubernetes_pod_name)(lumio_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"inbound\",network_id=\"Public\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Network Connections (Outgoing)",
   "type": "graph",
   "description": "Number of  Outbound Network Connections as measured by LumioNet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, kubernetes_pod_name)(lumio_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"outbound\",network_id=\"Public\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\"}[$interval])) by (instance)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", pod=~\"$kubernetes_pod_name.*fullnode.*\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", pod=~\"$kubernetes_pod_name.*fullnode.*\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Percentage Disk Used (global)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", persistentvolumeclaim=~\"fn.$kubernetes_pod_name.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", persistentvolumeclaim=~\"fn.$kubernetes_pod_name.*\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{persistentvolumeclaim}}:{{namespace}}"
    },
    {
     "expr": "1 - kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$kubernetes_pod_name.*fullnode.*\", kubernetes_pod_name!~\"val.*\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$kubernetes_pod_name.*fullnode.*\", kubernetes_pod_name!~\"val.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}:{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"fullnode\", pod=~\"$kubernetes_pod_name.*\", job=\"kubernetes-cadvisor\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"fullnode\", kubernetes_pod_name=~\"$kubernetes_pod_name\", cluster=\"$cluster\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{pod}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"fullnode\", pod=~\"pfn.*\", cluster=\"$cluster\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"fullnode\", pod=~\"$kubernetes_pod_name.*\", job=\"kubernetes-cadvisor\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}