{
 "title": "component-health-dashboard",
 "time": { "from": "now-4d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   { "name": "container", "query": { "query": "label_values(container)" } },
   { "name": "network_id", "query": { "query": "label_values(network_id)" } },
   { "name": "requesttype", "label": "RequestType", "query": "single,batch" },
   {
    "name": "method",
    "label": "JSON-RPC Method",
    "query": "submit, get_account, get_account_transaction, get_account_transactions, get_transactions, get_events, get_metadata, get_currencies, get_state_proof, get_account_state_with_proof"
   },
   { "name": "AggInterval", "label": "Aggregation interval", "query": "1m,5m,15m,30m,1h,3h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "description": "The rate of the committed round number.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_consensus_last_committed_round{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to commit",
   "type": "graph",
   "description": "Duration between block generation time until the moment it's committed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "s" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_consensus_block_tracing_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", stage=\"committed\"}[$AggInterval])/rate(lumio_consensus_block_tracing_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", stage=\"committed\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}: QC"
    }
   ]
  },
  {
   "title": "Timeout Rounds Rate",
   "type": "graph",
   "description": "The total number of rounds that have timeout certificate.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "count timeout rounds" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_consensus_timeout_rounds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Local Timeout rate",
   "type": "graph",
   "description": "The total number a single node has timeout locally. When 2f+1 nodes have local timeout for the same round, a timeout round is formed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "count timeouts" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_consensus_timeout_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "The error rate of main loop (timeout is considered as error)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_consensus_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]) / on (kubernetes_pod_name) rate(consensus_duration_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", op='main_loop'}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block execution time [P50]",
   "type": "graph",
   "description": "time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (kubernetes_pod_name, role, le)(rate(lumio_executor_execute_block_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block execution time [P90]",
   "type": "graph",
   "description": " time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (kubernetes_pod_name, role, le)(rate(lumio_executor_execute_block_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block execution time [P99]",
   "type": "graph",
   "description": "time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (kubernetes_pod_name, role, le) (rate(lumio_executor_execute_block_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [P50]",
   "type": "graph",
   "description": "the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (kubernetes_pod_name, role, le)(rate(lumio_executor_commit_blocks_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [P90]",
   "type": "graph",
   "description": "the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (kubernetes_pod_name, role, le)(rate(lumio_executor_commit_blocks_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [P99]",
   "type": "graph",
   "description": "the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (kubernetes_pod_name, role, le)(rate(lumio_executor_commit_blocks_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Key Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors Encountered (Last Hour)",
   "type": "graph",
   "description": "This panel tracks the number of errors encountered by the key manager during execution in the last hour. More specifically, we track two error types: (i) liveness errors; and (ii) unexpected errors.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Number of errors" }
   ],
   "targets": [
    {
     "expr": "increase(lumio_key_manager_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", state=\"liveness_error_encountered\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1h])",
     "legendFormat": "{{kubernetes_pod_name}}_liveness_error"
    },
    {
     "expr": "increase(lumio_key_manager_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", state=\"unexpected_error_encountered\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1h])",
     "legendFormat": "{{kubernetes_pod_name}}_unexpected_error"
    }
   ]
  },
  {
   "title": "No Action Taken (Last Hour)",
   "type": "graph",
   "description": "This panel tracks the number of times the key manager decides to take no action after checking the keys because the keys are still fresh (in the last hour).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Number of no actions taken" }
   ],
   "targets": [
    {
     "expr": "increase(lumio_key_manager_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", state=\"keys_still_fresh\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1h])",
     "legendFormat": "{{kubernetes_pod_name}}_keys_still_fresh"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers.  There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lumio_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"inbound\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Outbound Connected Peers",
   "type": "graph",
   "description": "Total Outbound connected peers.  There should be at most one peer with 0 Outbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lumio_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"outbound\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mempool size",
   "type": "graph",
   "description": "total number of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lumio_core_mempool_index_size{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\",kubernetes_pod_name=~\"$kubernetes_pod_name\",index=\"system_ttl\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Outgoing Txns Rate (Broadcasted)",
   "type": "graph",
   "description": "rate of transactions broadcasted to other peers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role) (rate(lumio_shared_mempool_transaction_broadcast_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Safety Rules",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error Counts of Queries",
   "type": "graph",
   "description": "This panel displays the error counts encountered by safety rules queries within the last aggregation interval.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    {
     "format": "short",
     "label": "Error Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(lumio_safety_rules_queries{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", result=\"error\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}_{{method}}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "graph",
   "description": "The most recent epoch processed by safety rules",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "Epoch Number" }
   ],
   "targets": [
    {
     "expr": "lumio_safety_rules_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", field=\"epoch\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Last Voted Round",
   "type": "graph",
   "description": "The last round that the validator submitted a vote",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "Round Number" }
   ],
   "targets": [
    {
     "expr": "lumio_safety_rules_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", field=\"last_voted_round\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Preferred Round",
   "type": "graph",
   "description": "The highest parent round from any incoming quorum certificate",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "Round Number" }
   ],
   "targets": [
    {
     "expr": "lumio_safety_rules_state{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", field=\"preferred_round\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SchemaDB get() Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "repeat": "cf_name",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_schemadb_get_latency_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])/rate(lumio_schemadb_get_latency_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Language/VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "User Transactions (Successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_vm_user_transactions_executed{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",status=\"success\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "System Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_vm_system_transactions_executed{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Txn Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_vm_txn_total_seconds_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[1m])/rate(lumio_vm_txn_total_seconds_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "JSON-RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JSON-RPC Request Count",
   "type": "graph",
   "description": "RPC endpoint level request count.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, type) (rate(lumio_client_service_rpc_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", type=~\"$requesttype\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{type}}"
    }
   ]
  },
  {
   "title": "JSON-RPC method internal errors",
   "type": "graph",
   "description": "Internal error rate, likely a bug if there is data show up.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, method, errorcode) (rate(lumio_client_service_internal_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", type=~\"$requesttype\", method=~\"$method\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{method}} {{errortype}}"
    }
   ]
  },
  {
   "title": "JSON-RPC method invalid requests",
   "type": "graph",
   "description": "The rate of invalid requests, all client side errors. ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role, method, errortype) (rate(lumio_client_service_invalid_requests_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", type=~\"$requesttype\", method=~\"$method\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{method}} {{errortype}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Request Latency [P50]",
   "type": "graph",
   "description": "This latency is recorded at JSON-RPC handler level without knowing what method is called. There are 2 types, batch and single requests.  \nBatch request is total time for all methods call finished.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum  by (kubernetes_pod_name, role, le)(rate(lumio_client_service_rpc_request_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\",type=~\"$requesttype\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Request Latency [P90]",
   "type": "graph",
   "description": "This latency is recorded at JSON-RPC handler level without knowing what method is called. There are 2 types, batch and single requests.  \nBatch request is total time for all methods call finished.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum  by (kubernetes_pod_name, role, le)(rate(lumio_client_service_rpc_request_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\",type=~\"$requesttype\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Request Latency [P99]",
   "type": "graph",
   "description": "This latency is recorded at JSON-RPC handler level without knowing what method is called. There are 2 types, batch and single requests.  \nBatch request is total time for all methods call finished.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum  by (kubernetes_pod_name, role, le)(rate(lumio_client_service_rpc_request_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\",type=~\"$requesttype\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logging Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "The rate of logs written via the code.  This is a superset of logs written through to the end log storage system.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "none", "label": "logs/s" }
   ],
   "targets": [
    {
     "expr": "rate(lumio_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Logging Total Failure Rate ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "The end to end rate of logs being submitted, to actually being sent to Logstash.  If this value rises above 0, see the corresponding error graphs to determine the issue.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 113 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Dropped" }
   ],
   "targets": [
    {
     "expr": "1-(rate(lumio_struct_log_tcp_submit_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])/rate(lumio_struct_log_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Connect Error Rate  ($AggInterval) [$kubernetes_pod_name-$role]",
   "type": "graph",
   "description": "Percentage of connections that fail to connect to the logging pod.  Extended or high percentage e.g. 100% connections points to a dead logging pod.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 113 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent Connections Failed" }
   ],
   "targets": [
    {
     "expr": "(rate(lumio_struct_log_connect_error_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval]) or 0 * rate(lumio_struct_log_tcp_connect_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])) / rate(lumio_struct_log_tcp_connect_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  }
 ]
}