{
 "title": "state-sync-v2",
 "description": "State sync v2 dashboard",
 "tags": [ "lumio-core" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, role)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "State Sync Driver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest synced version",
   "type": "timeseries",
   "description": "The latest synced version of the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "lumio_state_sync_version{cluster=~\"$cluster\", chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Latest synced version",
   "type": "bargauge",
   "description": "The latest synced version.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lumio_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Sync lag (behind highest known)",
   "type": "timeseries",
   "description": "The difference between the highest advertised version and the currently synced version.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "clamp_min (lumio_data_client_highest_advertised_data{cluster=~\"$cluster\", chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", data_type=\"transactions\"} - on(cluster,kubernetes_pod_name,role, namespace) lumio_state_sync_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced\"}, 0)",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Syncing throughput (versions per second)",
   "type": "timeseries",
   "description": "The storage synchronizer throughput (versions per second).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(lumio_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",type=\"synced\"}[$interval])",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{type}}"
    },
    {
     "expr": "rate(lumio_state_sync_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",type=\"synced_states\"}[$interval])",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{type}}"
    }
   ]
  },
  {
   "title": "Latest synced epoch",
   "type": "timeseries",
   "description": "The highest synced epoch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "lumio_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", type=\"synced_epoch\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{type}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer versions (per operation)",
   "type": "timeseries",
   "description": "The storage synchronizer version per operation type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "lumio_state_sync_version{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{type}}"
    }
   ]
  },
  {
   "title": "Driver events (per second)",
   "type": "timeseries",
   "description": "The driver events per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(lumio_state_sync_driver_counters{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Executing component",
   "type": "timeseries",
   "description": "The component currently executing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(lumio_state_sync_executing_component_counters{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) > 0",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Execute/Apply latencies",
   "type": "timeseries",
   "description": "The latencies of execute/apply operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"execute_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Execute (P99)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"apply_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Apply (P99)"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"execute_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Execute (P70)"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"apply_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Apply (P70)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"execute_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Execute (P50)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"apply_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Apply (P50)"
    }
   ]
  },
  {
   "title": "Average Execute/Apply latencies",
   "type": "timeseries",
   "description": "The latencies of execute/apply operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lumio_state_sync_storage_synchronizer_latencies_sum{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"apply_chunk\"}/lumio_state_sync_storage_synchronizer_latencies_count{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"apply_chunk\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    },
    {
     "expr": "lumio_state_sync_storage_synchronizer_latencies_sum{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"execute_chunk\"}/lumio_state_sync_storage_synchronizer_latencies_count{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"execute_chunk\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Commit latencies",
   "type": "timeseries",
   "description": "The latencies of commit operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"commit_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Commit (P99)"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"commit_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Commit (P70)"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(lumio_state_sync_storage_synchronizer_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"commit_chunk\"}[$__rate_interval])) by (le))",
     "legendFormat": "Commit (P50)"
    }
   ]
  },
  {
   "title": "Average commit latencies",
   "type": "timeseries",
   "description": "The latencies of commit operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "lumio_state_sync_storage_synchronizer_latencies_sum{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"commit_chunk\"}/lumio_state_sync_storage_synchronizer_latencies_count{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"commit_chunk\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Average executed chunk sizes",
   "type": "timeseries",
   "description": "The chunk sizes of executed transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lumio_state_sync_storage_synchronizer_chunk_sizes_sum{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"executed_transactions\"}/lumio_state_sync_storage_synchronizer_chunk_sizes_count{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"executed_transactions\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Average applied chunk sizes",
   "type": "timeseries",
   "description": "The chunk sizes of transaction outputs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lumio_state_sync_storage_synchronizer_chunk_sizes_sum{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"applied_transaction_outputs\"}/lumio_state_sync_storage_synchronizer_chunk_sizes_count{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"applied_transaction_outputs\"} ",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer gauges",
   "type": "timeseries",
   "description": "The storage synchronizer gauges",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "lumio_state_sync_storage_synchronizer_gauges{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Number of state values (on-chain)",
   "type": "timeseries",
   "description": "The number of state values currently held on-chain.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "lumio_jellyfish_leaf_count{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
    }
   ]
  },
  {
   "title": "Bootstrapper errors (per second)",
   "type": "timeseries",
   "description": "The bootstrapper errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "rate(lumio_state_sync_bootstrapper_errors{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Storage synchronizer errors (per second)",
   "type": "timeseries",
   "description": "The storage synchronizer errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "rate(lumio_state_sync_storage_synchronizer_errors{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Fallback mode status",
   "type": "timeseries",
   "description": "Whether or not fallback mode has been engaged",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "lumio_state_sync_driver_fallback_mode{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{label}}"
    }
   ]
  },
  {
   "title": "Continuous syncer errors (per second)",
   "type": "timeseries",
   "description": "The continuous syncer errors per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(lumio_state_sync_continuous_syncer_errors{chain_name=~\"$chain_name\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_label}}"
    }
   ]
  },
  {
   "title": "Data Streaming Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active data streams",
     "type": "timeseries",
     "description": "The number of active data streams.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "lumio_data_streaming_service_active_data_streams{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "In-flight data requests",
     "type": "timeseries",
     "description": "The number of pending in-flight data requests",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "lumio_data_streaming_service_pending_data_responses{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "Created data streams (per second)",
     "type": "timeseries",
     "description": "The data streams created per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_create_data_stream{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Terminated data streams (per second)",
     "type": "timeseries",
     "description": "The data streams terminated per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_terminate_data_stream{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{feedback_type}}"
      }
     ]
    },
    {
     "title": "Created subscription streams (per second)",
     "type": "timeseries",
     "description": "The subscription streams created per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_create_subscription_stream{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Terminated subscription streams (per second)",
     "type": "timeseries",
     "description": "The subscription streams terminated per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_terminate_subscription_stream{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{termination_reason}}"
      }
     ]
    },
    {
     "title": "Sent data requests (per second)",
     "type": "timeseries",
     "description": "The sent data requests per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_sent_data_requests{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Received data responses (per second)",
     "type": "timeseries",
     "description": "The data responses received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_received_data_response{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Average request processing latencies (per type)",
     "type": "timeseries",
     "description": "The average request processing latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lumio_data_streaming_service_data_request_processing_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/lumio_data_streaming_service_data_request_processing_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Request processing latencies",
     "type": "timeseries",
     "description": "The 0.99 quantile of all request processing latencies.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_data_streaming_service_data_request_processing_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_data_streaming_service_data_request_processing_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_data_streaming_service_data_request_processing_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Average response chunk sizes",
     "type": "timeseries",
     "description": "The average response chunk sizes per type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lumio_data_streaming_service_received_data_chunk_sizes_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/lumio_data_streaming_service_received_data_chunk_sizes_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Retried data requests (per second)",
     "type": "timeseries",
     "description": "The retried data requests per second (with new timeouts in ms).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_retried_data_requests{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{request_timeout}}"
      }
     ]
    },
    {
     "title": "Missing data requests (per second)",
     "type": "timeseries",
     "description": "The data requests for missing data per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_sent_data_requests_for_missing_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Received response errors (per second)",
     "type": "timeseries",
     "description": "The data response errors received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_received_response_error{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "Check progress errors (per second)",
     "type": "timeseries",
     "description": "The check progress errors encountered per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_check_progress_error{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "Global data summary errors (per second)",
     "type": "timeseries",
     "description": "The global data summary errors encountered per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "targets": [
      {
       "expr": "rate(lumio_data_streaming_service_global_summary_error{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    },
    {
     "title": "Data stream send failures",
     "type": "timeseries",
     "description": "The number of send failures encountered.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "targets": [
      {
       "expr": "lumio_data_streaming_service_stream_send_failure{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lumio Data Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In-flight polls",
     "type": "timeseries",
     "description": "The number of in-flight polls currently executing",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "lumio_data_client_in_flight_polls{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{peer_type}}"
      }
     ]
    },
    {
     "title": "Connected peers (including priorities)",
     "type": "timeseries",
     "description": "The number of connected peers by priority types",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "targets": [
      {
       "expr": "lumio_data_client_connected_peers{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{peer_type}}"
      }
     ]
    },
    {
     "title": "Sent requests (per second)",
     "type": "timeseries",
     "description": "The sent data requests per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "rate(lumio_data_client_sent_requests{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_types}}-{{network}}"
      }
     ]
    },
    {
     "title": "Successful responses (per second)",
     "type": "timeseries",
     "description": "The successful data responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "targets": [
      {
       "expr": "rate(lumio_data_client_success_responses{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{response_type}}-{{network}}"
      }
     ]
    },
    {
     "title": "Error responses (per second)",
     "type": "timeseries",
     "description": "The error responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "targets": [
      {
       "expr": "rate(lumio_data_client_error_responses{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{response_type}}-{{network}}"
      }
     ]
    },
    {
     "title": "Average request latencies (per type)",
     "type": "timeseries",
     "description": "The average request latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lumio_data_client_request_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/lumio_data_client_request_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network}}"
      }
     ]
    },
    {
     "title": "Request latencies",
     "type": "timeseries",
     "description": "The latencies of all requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_data_client_request_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_data_client_request_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_data_client_request_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Optimal chunk sizes (per type)",
     "type": "timeseries",
     "description": "The optimal chunk sizes per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
     "targets": [
      {
       "expr": "lumio_data_client_optimal_chunk_sizes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{data_type}}"
      }
     ]
    },
    {
     "title": "Highest advertised transaction data",
     "type": "bargauge",
     "description": "The highest advertised transaction data.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lumio_data_client_highest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",data_type=\"transactions\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Highest advertised data (per type)",
     "type": "timeseries",
     "description": "The highest advertised data version per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
     "targets": [
      {
       "expr": "lumio_data_client_highest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{data_type}}"
      }
     ]
    },
    {
     "title": "Lowest advertised transaction data",
     "type": "bargauge",
     "description": "The lowest advertised transaction data.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lumio_data_client_lowest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",data_type=\"transactions\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Lowest advertised data (per type)",
     "type": "timeseries",
     "description": "The lowest advertised data version per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
     "targets": [
      {
       "expr": "lumio_data_client_lowest_advertised_data{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{data_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Service Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests received (per second)",
     "type": "timeseries",
     "description": "The requests received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_requests_received{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Storage responses sent (per second)",
     "type": "timeseries",
     "description": "The storage responses sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_responses_sent{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{response_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Request processing latencies",
     "type": "timeseries",
     "description": "The latencies for storage request processing",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_storage_service_server_request_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_storage_service_server_request_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_storage_service_server_request_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Average request processing latencies (per type)",
     "type": "timeseries",
     "description": "The average request processing latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lumio_storage_service_server_request_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/lumio_storage_service_server_request_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Storage errors (per second)",
     "type": "timeseries",
     "description": "The storage errors per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_errors{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{error_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Number of ignored peers",
     "type": "timeseries",
     "description": "The number of peers currently being ignored",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lumio_storage_service_server_ignored_peer_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Pending network events (per second)",
     "type": "timeseries",
     "description": "The pending network events per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{state}}"
      }
     ]
    },
    {
     "title": "Network frame overflow (count per second)",
     "type": "timeseries",
     "description": "The rate of network frame overflows when handling storage requests (per second).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_network_frame_overflow{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "LRU storage cache (Hit Rate)",
     "type": "timeseries",
     "description": "The hit rate (percentage) of the LRU storage cache per cache probe.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name, role, network_id) (lumio_storage_service_server_lru_cache{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", event=\"lru_cache_hit\"}) / sum by (kubernetes_pod_name, role, network_id) (lumio_storage_service_server_lru_cache{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", event=\"lru_cache_probe\"}) * 100\n",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Active optimistic fetches",
     "type": "timeseries",
     "description": "The number of active optimistic fetches at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lumio_storage_service_server_optimistic_fetch_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "New optimistic fetch events (per second)",
     "type": "timeseries",
     "description": "New optimistic fetch events seen at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_optimistic_fetch_event{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",event=\"optimistic_fetch_add\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Expired optimistic fetch events (per second)",
     "type": "timeseries",
     "description": "Expired optimistic fetch events seen at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_optimistic_fetch_event{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",event=\"optimistic_fetch_expire\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Average optimistic fetch latencies",
     "type": "timeseries",
     "description": "The average latencies to handle optimistic fetch requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lumio_storage_service_server_optimistic_fetch_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/lumio_storage_service_server_optimistic_fetch_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Optimistic fetch latencies",
     "type": "timeseries",
     "description": "The latencies for handling optimistic fetch requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_storage_service_server_optimistic_fetch_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_storage_service_server_optimistic_fetch_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_storage_service_server_optimistic_fetch_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Active subscriptions",
     "type": "timeseries",
     "description": "The number of active subscriptions at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lumio_storage_service_server_subscription_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1m]",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "New subscription events (per second)",
     "type": "timeseries",
     "description": "New subscription events seen at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_subscription_event{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",event=\"subscription_add\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{event}}"
      }
     ]
    },
    {
     "title": "Expired subscription events (per second)",
     "type": "timeseries",
     "description": "Expired subscription events seen at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_subscription_event{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",event=\"subscription_expire\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{event}}"
      }
     ]
    },
    {
     "title": "Failed subscription events (per second)",
     "type": "timeseries",
     "description": "Failed subscription events seen at the server.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lumio_storage_service_server_subscription_event{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",event=\"subscription_failure\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{event}}"
      }
     ]
    },
    {
     "title": "Average subscription latencies",
     "type": "timeseries",
     "description": "The average latencies to handle subscription requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lumio_storage_service_server_subscription_latency_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/lumio_storage_service_server_subscription_latency_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{request_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Subscription latencies",
     "type": "timeseries",
     "description": "The latencies for handling subscription requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_storage_service_server_subscription_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_storage_service_server_subscription_latency_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average propose to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The average latencies taken from when data is first proposed, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(lumio_data_client_sync_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_sync_latency\"}[1m])/rate(lumio_data_client_sync_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_sync_latency\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
      }
     ]
    },
    {
     "title": "Propose to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The latencies taken from when data is first proposed, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Average propose to sync latencies: state sync only (seconds)",
     "type": "timeseries",
     "description": "The average latencies taken from when data is first proposed, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(lumio_data_client_sync_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_sync_latency\"}[1m])/rate(lumio_data_client_sync_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_sync_latency\"}[1m])\n-\nquantile(0.67, rate(lumio_consensus_block_tracing_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval]) / rate(lumio_consensus_block_tracing_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval])) < 1000000",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
      }
     ]
    },
    {
     "title": "Propose to sync latencies: state sync only (seconds)",
     "type": "timeseries",
     "description": "The latencies taken from when data is first proposed, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))\n-\nquantile(0.67, rate(lumio_consensus_block_tracing_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval]) / rate(lumio_consensus_block_tracing_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval])) < 1000000",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))\n-\nquantile(0.67, rate(lumio_consensus_block_tracing_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval]) / rate(lumio_consensus_block_tracing_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval])) < 1000000",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_sync_latency\"}[$__rate_interval])) by (le))\n-\nquantile(0.67, rate(lumio_consensus_block_tracing_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval]) / rate(lumio_consensus_block_tracing_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", role=\"validator\", stage=\"committed\"}[$interval])) < 1000000",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Average propose to seen latencies (seconds)",
     "type": "timeseries",
     "description": "The average latencies taken from when data is first proposed, to when it is finally seen.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rate(lumio_data_client_sync_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_seen_latency\"}[1m])/rate(lumio_data_client_sync_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"propose_to_seen_latency\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
      }
     ]
    },
    {
     "title": "Propose to seen latencies (seconds)",
     "type": "timeseries",
     "description": "The latencies taken from when data is first proposed, to when it is finally seen.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_seen_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_seen_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"propose_to_seen_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Average seen to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The average latencies taken from when data is first seen, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "rate(lumio_data_client_sync_latencies_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"seen_to_sync_latency\"}[1m])/rate(lumio_data_client_sync_latencies_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", label=\"seen_to_sync_latency\"}[1m])",
       "legendFormat": "{{namespace}}-{{kubernetes_pod_name}}-{{role}}-{{label}}"
      }
     ]
    },
    {
     "title": "Seen to sync latencies (seconds)",
     "type": "timeseries",
     "description": "The latencies taken from when data is first seen, to when it is finally synced.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"seen_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"seen_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(lumio_data_client_sync_latencies_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",label=\"seen_to_sync_latency\"}[$__rate_interval])) by (le))",
       "legendFormat": "P50"
      }
     ]
    }
   ]
  }
 ]
}