name: "CLI Rust Setup"
description: "Setup the rust toolchain and cache for the CLI build"
inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git"
    required: false
  SSH_KEY:
    description: "Optional SSH private key for private dependencies"
    required: false
  ADDITIONAL_KEY:
    description: "An optional additional key to pass to rust-cache"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - run: echo "HELLO FROM UPDATED ACTION"
      shell: bash
    - uses: dsherret/rust-toolchain-file@v1
    - name: Install build tools
      shell: bash
      run: scripts/cli/minimal_cli_build.sh
    - run: echo "/home/runner/.cargo/bin" | tee -a $GITHUB_PATH
      shell: bash
    - name: Setup git credentials
      shell: bash
      run: |
        # Ensure github.com is in known_hosts
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
        # If SSH_KEY is provided, write it to file and configure git
        if [ -n "${{ inputs.SSH_KEY }}" ]; then
          echo "Setting up SSH key from input..."
          echo "${{ inputs.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Start ssh-agent manually if needed, or just let git use the file
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          
          # Configure git to use ssh explicitly if needed
          git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=~/.ssh/known_hosts"
        fi
        
        # Debug SSH connection
        echo "=== SSH Debug Info ==="
        ssh-add -l || echo "No keys in agent"
        ssh -v -T git@github.com || true
        echo "======================"
        
        # Clean up any previous HTTPS/Cargo config overrides
        rm -rf ~/.cargo/config.toml .cargo/config.toml
        rm -rf ~/.cargo/git/db/*

    # Display the rust toolchain version being installed
    - name: Setup rust toolchain
      shell: bash
      run: rustup show
